language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=1.8.17
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.6

install:
  - pip install coverage coveralls
  - pip install psycopg2
  - pip install -q Django==$DJANGO_VERSION

before_script:
  - psql -c 'create database pgcryptoauth_test;' -U postgres

script:
  coverage run --source=pgcryptoauth runtests.py

after_success:
  coveralls
